import { ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import Head from 'next/head';

import theme from '@/styles/theme/constants';

import '@/styles/reset.scss';

export const metadata: Metadata = {
  title: 'Svoy App!!!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Svoy App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
